# Generated by Django 3.0.7 on 2022-01-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='person_name')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age ')),
                ('date', models.DateField(null=True)),
                ('address', models.EmailField(blank=True, default='', max_length=120, null=True, verbose_name='address')),
            ],
        ),
    ]
