# Generated by Django 3.0.7 on 2022-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
