# Generated by Django 3.0.7 on 2022-02-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_auto_20220212_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
