# Generated by Django 3.0.7 on 2022-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0008_auto_20220212_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
