# Generated by Django 3.0.7 on 2022-02-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0010_auto_20220212_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
