# Generated by Django 3.0.7 on 2022-02-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0011_person_hotel_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age ')),
                ('service_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mobile_app.person')),
            ],
        ),
    ]
